project_id: devx-tsc
dataset: sample_dataset_5
location: US

api:
  url: "https://randomuser.me/api/"
  params:
    results: 10
    seed: easytest

tables:
  raw_table: raw_api_data

  normalized_tables:
    - users_user
    - users_location
    - users_login
    - users_assets
    - users_contact

  system_tables:
    - pipeline_metrics
    - pipeline_audit_logs

pipeline:
  max_retries: 3
  retry_delay: 5